
[phases.setup]

nixPkgs = ["python311"]



[phases.install]

cmds = ["pip install -r requirements.txt"]



[phases.build]

cmds = ["python manage.py migrate --noinput"]



[start]

cmd = "gunicorn blending_project.wsgi:application --bind 0.0.0.0:$PORT"

