[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn blending_project.wsgi:application --bind 0.0.0.0:$PORT"
preDeployCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput"
